### ISSUE TITLE
the birday paradox code seems to be wrong

### ISSUE THREAD

**Issue by xiaoouwang** [rkneusel9/MathForDeepLearning#2]
Given the following code, the pairs are actually selected such as the order matters (so ab and ba are considered different). The right approach is to choose pairs without considering order (so ba shouldn't compared again).

```py
for m in range(2, M+1):
    matches = 0
    for n in range(N):
        match = 0
        # define a random birthday for each person of m
        b = np.random.randint(0, 364, m)
        # print(b)
        # break
        for i in range(m):
            for j in range(m):
                if (i != j) and (b[i] == b[j]):
                    match += 1
        if (match != 0):
            matches += 1
```
Based on the above reasoning, the j loop should start from i (`for j in range (i,m)`) to avoid duplicates. After making this minor modification, the threshold to surpass 50% remains 23 but the code is mathematically correct now.

I've made a push request on this issue.

**Comment by rkneusel9** [comment]
Double counting is fine.  The increment to "matches" is concerned with at least one match, meaning "match" isn't zero.  It'll run a little faster with your change, but speed isn't the goal.  The code is mathematically correct.

**Comment by xiaoouwang** [comment]
Oh I see your point but still it is not coherent with the text, especially with the combination part :)
